name: go
on:
    push:
        branches:
            - master
    pull_request:

env:
    GOPRIVATE: github.com/NextronSystems/

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: stable
            - name: Use token
              run: git config --global url."https://${{ secrets.JSONLOG_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
            - name: Test
              run: go test -v ./...
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: stable
            - name: Use token
              run: git config --global url."https://${{ secrets.JSONLOG_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
            - name: Lint
              uses: golangci/golangci-lint-action@v8
              with:
                  version: v2.1.6
